baseURL = 'https://wlpretorius.github.io/'
languageCode = 'en-us'
title = 'Willem Pretorius'
theme = 'hugo-coder'
paginate = 20
enableEmoji = true

[markup.highlight]
noClasses = false

[params]
  author = "Willem Pretorius"
  description = "Willem Pretorius's personal website"
  info = ["Credit Risk Expert | Quant | Financial Engineer"]
  #dateFormat = "20 March 2024"
  since = 2024
  colorScheme = "dark"
  hideColorSchemeToggle = false
  customCSS = []
  customSCSS = []
  customJS = []
  customRemoteJS = []

    [taxonomies]
    category = "categories"
    series = "series"

    [params.goatCounter]
    code = "wlpretorius"

    [[params.social]]
    name = "LinkedIn"
    icon = "fa-brands fa-linkedin fa-2x"
    weight = 1
    url = "https://www.linkedin.com/in/wlpretorius/"

    [[params.social]]
    name = "Medium"
    icon = "fa-brands fa-medium fa-2x"
    weight = 2
    url = "https://medium.com/@willempretorius"

    [[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"

    [[menu.main]]
    name = "Posts"
    weight = 2
    url = "/posts/"

    [[menu.main]]
    name = "Expertise"
    weight = 3
    url = "/expertise/expertise"   

    [[menu.main]]
    name = "Regulations"
    weight = 4
    url = "/regulations/regulations"   

    [[menu.main]]
    name = "Academic Papers"
    weight = 5
    url = "/papers/papers"

    [[menu.main]]
    name = "Books"
    weight = 6
    url = "/books/books"

    [[menu.main]]
    name = "Contact me"
    weight = 7
    url = "/contact/"