baseURL = 'https://wlpretorius.github.io/'
languageCode = 'en-us'
title = 'Willem Pretorius'
theme = 'hugo-coder'
paginate = 20
enableEmoji = true

[markup.highlight]
noClasses = false

[params]
  author = "Willem Pretorius"
  description = "Willem Pretorius's personal website"
  info = ["Credit Risk Modeller | Quant | Financial Engineer"]
  dateFormat = "20 March 2024"
  since = 2024
  colorScheme = "dark"
  hideColorSchemeToggle = false

    [[params.social]]
    name = "LinkedIn"
    icon = "fa-brands fa-linkedin fa-2x"
    weight = 1
    url = "https://www.linkedin.com/in/wlpretorius/"

    [[params.social]]
    name = "Medium"
    icon = "fa-brands fa-medium fa-2x"
    weight = 2
    url = "https://medium.com/@willempretorius"

    [[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"