baseURL = 'https://wlpretorius.github.io/'
languageCode = 'en-us'
title = 'Willem Pretorius'
theme = 'hugo-coder'
paginate = 20
enableEmoji = true

[markup.highlight]
noClasses = false

[params]
  author = "Willem Pretorius"
  description = "Willem Pretorius's personal website"
  info = ["Credit Risk Modeller | Quant | Financial Engineer"]
  dateFormat = "20 March 2024"
  since = 2024
  colorScheme = "dark"
  hideColorSchemeToggle = false
  maxSeeAlsoItems = 5